files/default/postgres-appliance/scripts/configure_spilo.py
set to 1/1000 of available memory, clamped to 16MB-64MB
Users can still override this setting on a per connection basis using `SET work_mem`, and the default setting can be overridden by setting the SPILO_CONFIGURATION env var. [Some relevant info on this](https://github.com/zalando/spilo/issues/337).
=> increase default work_mem

columnar/src/backend/columnar/columnar_reader.c, columnar/src/backend/columnar/vectorization/columnar_vector_types.c, columnar/src/test/regress/expected/columnar_alter_set_type.out, columnar/src/test/regress/expected/columnar_query.out, columnar/src/test/regress/sql/columnar_query.sql
Fixes #46. Handling now types which have `len` larger that 8 byte by directly copying value.
=> [columnar] fixes types larger than 8 bytes

columnar/src/backend/columnar/columnar_customscan.c, columnar/src/backend/columnar/columnar_metadata.c, columnar/src/backend/columnar/columnar_reader.c, columnar/src/backend/columnar/columnar_tableam.c, columnar/src/include/columnar/columnar.h, columnar/src/include/columnar/columnar_metadata.h, columnar/src/test/regress/expected/columnar_vacuum.out, columnar/src/test/regress/sql/columnar_vacuum.sql
Vacuum columnar tables by combining last n stripes until stripe row max count is reached. Vacuuming decision also include information about number of deleted rows of each stripe. If there is only one stripe, vacuum will be done if percentage of deleted rows is higher than 20%.
=> [columnar] Columnar vacuum

Dockerfile, Dockerfile.spilo, docker-bake.hcl, third-party/ivm/Dockerfile
This adds `pg_ivm` to the base hydra image as per #58.
=> Add pg_ivm to the base hydra image

columnar/src/backend/columnar/columnar_metadata.c
When assigning next stripe to be read, workers need to scan complete stripe metadata table and reach stripe which need to be read next. During this fetch and compare of stripe metadata rows memory is never released for stripes that needs to be skipped.
This should be addressed by releasing memory that is not needed.
=> [columnar] [Bug] Sequential scan parallel execution OOM

columnar/src/backend/columnar/columnar_metadata.c, columnar/src/backend/columnar/columnar_tableam.c
During vacuum, stripes are collected in reverse order and if row number is greater than defined limit we should stop and combine previous stripe into them into one. Problem is that while writing rows into temporary write state object - this condition is not greater but greater or equal which lead to infinite loop. Fixed by using proper comparison operator when stripe candidates are choosen.
=> [columnar] [Bug]: Vacuum still fails by hanging indefinitely

README.md
This pull requests makes the README's Contents section clickable to allow jumping to the section directly.
Add links in Contents section of README
=> Add link from Contents to the README sections

.github/workflows/build_spilo.yaml, .github/workflows/ci.yaml
Per https://github.com/hydradatabase/hydra/pull/82#issuecomment-1551898003 there was a job that ran for almost 2 hours (!) that should have run for only a few minutes.
I think these timeouts are well above what is needed if these are running correctly.
=> add timeouts to all jobs

CHANGELOG.md, columnar/src/backend/columnar/columnar_tableam.c, columnar/src/test/regress/expected/columnar_vacuum_udf.out, columnar/src/test/regress/expected/columnar_vacuum_udf_1.out, columnar/src/test/regress/sql/columnar_vacuum_udf.sql
Fixes an issue where when using the vacuum UDF, a loop can occur that can cause stripes to continually move and eventually overwrite.
* moved stripe list generation
* updated test
* updated expected results
=> [columnar] fix issue with vacuum udf looping

columnar/src/backend/columnar/columnar_customscan.c
Through the process of benchmarking, I found a regression that caused some queries to create such a bad plan that they never returned (I let them go for over 24 hours in some cases).
This is an attempt to fix that.  I've tried to strike a balance as much as I can, and did ~100 iterations of this PR to try to find the best balance.
Likely, we can spend more time and generate better plans (as found in the TPC-H like benchmarks), but this seemed to be a good compromise between never returning and faster in some cases.
Ultimately, we should not be messing with the `total_cost` as much as we are, and need to revisit what we would gain and lose from changing this value.
Tests were run with multiple values of parallelism, and the results had the same amount of variance.
Ultimately, I believe …
=> [columnar] Adjust plan for parallel workers

.github/workflows/ci.yaml
In most cases, the build is most likely to fail nearly simultaneously, so this will let each build run until it errors rather than aborting just before it was likely to fail, confirming the problem is not version specific.
In cases where the problem is version specific, this will inform us if the problem is actually specific to a particular version of Postgres.
=> [ci] turn off fail-fast for pg version matrix

Dockerfile, docker-bake.hcl, third-party/multicorn/Dockerfile
Spilo bases on ubuntu:jammy/ubuntu:22.04 which in turns bases on debian:bookworm. But the open source Postgres image still bases on debian:bullseye which can cause issues long term for extensions because the base image is different between Spilo & open source Postgres.
=> Upgrade open source Postgres image from bullseye to bookworm

.github/workflows/benchmark.yaml, .github/workflows/ci.yaml
More improvements to the benchmarking actions to match updates made to the [benchmarking scripts](https://github.com/hydradatabase/benchmarks). Test runs look good and should send everything to [bencher](https://bencher.dev/perf/hydra-postgres) once this is merged to `main`.
Benchmarks are not run on PRs at this time, as the benchmarks run against (i.e. pull) built images that have been published. PRs do not push images so this needs some more effort and thought.
Makes progress on #101.
=> automated benchmarking v3

Dockerfile, Dockerfile.spilo, acceptance/shared/cases.go, docker-bake.hcl, files/spilo/postgres-appliance/scripts/configure_spilo.py, third-party/pgxman_install.sh
* Install `pg_vector` extension with `pgxman`. Note that it's intentional to always force installing extensions with `pgxman` for now to avoid Docker layer caching in case there are any updates made to the extension packages.
* Add acceptance tests to validate `pg_vector` is working as expected.
A demo of `pg_vector` running with the built image:
```psql
postgres=# create extension vector;
CREATE EXTENSION
postgres=# CREATE TABLE items (id bigserial PRIMARY KEY, embedding vector(3));
CREATE TABLE
postgres=# INSERT INTO items (embedding) VALUES ('[1,2,3]'), ('[4,5,6]');
INSERT 0 2
postgres=# SELECT * FROM items ORDER BY embedding <-> '[3,1,2]' LIMIT 5;
id | embedding 
----+-----------
1 | [1,2,3]
2 | [4,5,6]
(2 rows)
```
=> Install `pg_vector` extension with `pgxman`

columnar/src/backend/columnar/columnar_cache.c
in the changeover from using a custom linked list solution to using `dlist`, the freeing of the `StringInfo` got lost.  this PR adds them back.
=> [columnar] Add back missing cache eviction pfree()s

third-party/pgxman_install.sh
Force install of pgxman debian package. 
Ref: https://github.com/hydradatabase/hydra/actions/runs/5661711378/job/15340883764
=> Force install of pgxman debian package

files/spilo/postgres-appliance/scripts/post_init.sh
this avoids double quoting since pg_catalog.quote_ident(datname) will add quotes if needed
=> spilo: remove quotes around db_name

columnar/src/backend/columnar/columnar_cache.c, columnar/src/backend/columnar/columnar_tableam.c, columnar/src/test/regress/expected/columnar_cache.out, columnar/src/test/regress/sql/columnar_cache.sql
While the `head` of the cache linked list should be created when a query is run, when a simple explain is run without running the query, the `head` is not initialized.
In addition, once it is initialized, it is not being set back to a full reset state of `NULL`. 
A check is now made against `head` being `NULL` before attempting to iterate the linked list, and `head` is set to `NULL` again when a new memory context is created for the query.  Since `head` is allocated in the query context, and the context is destroyed, this should be a-ok.
fixes #124
also, backports a check against another linked list that fails in `assert` when asserts are enabled.
=> [columnar] fixes a state where an explain with cache on can cause a crash

docker-compose.yml
fixes #130
This is the recommendation per the docs ( https://hub.docker.com/_/postgres/ ) that I was following, but I missed that they had `-c 'config_file=...'`.
=> set `-c config_file=` in docker-compose

columnar/src/backend/columnar/columnar_tableam.c, columnar/src/test/regress/expected/columnar_alter.out, columnar/src/test/regress/expected/columnar_alter_set_type.out, columnar/src/test/regress/expected/columnar_alter_table_set_access_method.out, columnar/src/test/regress/expected/columnar_indexes.out, columnar/src/test/regress/expected/columnar_paths.out, columnar/src/test/regress/expected/columnar_paths_1.out, columnar/src/test/regress/sql/columnar_alter.sql, columnar/src/test/regress/sql/columnar_indexes.sql, columnar/src/test/regress/sql/columnar_paths.sql
This PR expands the whitelist for which indexes are allowed to be created against a columnar table.
This does not mean that these indexes will be automatically used, in fact in many cases the indexes will not be used.  This just allows for additional indexes to be created which can be used either by explicitly disabling `columnar.enable_custom_scan` or by using a plan modification such as `pg_plan_hint`.
Newly supported indexes:
* `gin`
* `gist` - also supports postgis indexes and pg_embedding indexes
* `spgist`
* `rum` - external `gin`-like index type
Not supported:
* `brin` - difficult to support due to how it is tied into the storage
* `bloom` - supportable, but unable to get the index to be used, so left off white list, might be worth a second look later
=> [columnar] Update index whitelist to include GIN and GIST

columnar/Makefile
The command:
make install DESTDIR=/dst
Fails with:
make[1]: Leaving directory '/src/columnar/src/backend/columnar'
/usr/bin/install -c -m 644 ./src/include/citus_version.h '/dst/usr/include/postgresql/server/'
install: can't create '/dst/usr/include/postgresql/server/': No such file or directory
I guess it assumes this directory already exists from a PostgreSQL installation, but when using DESTDIR it may not exist in there yet, so make sure the directory exists.
=> Fix 'make install DESTDIR=..'

Dockerfile.spilo, third-party/pgxman/install.sh, third-party/pgxman/pgxman_14_spilo.yaml
The issue is due to the ordering of the pgxman file that 14 should override 13.
Ref: https://github.com/hydradatabase/hydra-internal/actions/runs/5969618453/job/16195791777
=> Fix Spilo CI

columnar/src/backend/columnar/Makefile, columnar/src/backend/columnar/columnar.c, columnar/src/backend/columnar/columnar.control, columnar/src/backend/columnar/columnar_customscan.c, columnar/src/backend/columnar/columnar_planner_hook.c, columnar/src/backend/columnar/columnar_reader.c, columnar/src/backend/columnar/columnar_tableam.c, columnar/src/backend/columnar/sql/columnar--11.1-8--11.1-9.sql, columnar/src/backend/columnar/vectorization/columnar_vector_execution.c, columnar/src/backend/columnar/vectorization/columnar_vector_types.c, columnar/src/backend/columnar/vectorization/nodes/columnar_aggregator_node.c, columnar/src/backend/columnar/vectorization/types/aggregates.c, columnar/src/backend/columnar/vectorization/types/int.c, columnar/src/backend/columnar/vectorization/types/numeric.c, columnar/src/include/columnar/columnar.h, columnar/src/include/columnar/columnar_customscan.h, columnar/src/include/columnar/utils/listutils.h, columnar/src/include/columnar/vectorization/columnar_vector_execution.h, columnar/src/include/columnar/vectorization/columnar_vector_types.h, columnar/src/include/columnar/vectorization/nodes/columnar_aggregator_node.h, columnar/src/include/columnar/vectorization/types/numeric.h, columnar/src/include/columnar/vectorization/types/types.h, columnar/src/test/regress/columnar_schedule, columnar/src/test/regress/expected/columnar_aggregates.out, columnar/src/test/regress/expected/columnar_aggregates_1.out, columnar/src/test/regress/expected/columnar_cache_1.out, columnar/src/test/regress/sql/columnar_aggregates.sql
Handle vacuum process with only one full stripe
* If there is only one stripe that is populated with maximum number of rows do nothing.
Vector read should count only non deleted rows
* When reading next vector for processing we should count only rows that are not deleted.
Vectorized direct aggregates
* Supported version 14/15
* Reused nodeAgg.c to handle vectorized aggregates
* Implementation of aggregate function to handle vector input
Add O3 optimization
* Uses O3 optimization. Flag will be used when `COLUMNAR_O3` is set.
=> [columnar] Vectorized direct aggregates

columnar/src/backend/columnar/columnar_cache.c, columnar/src/backend/columnar/columnar_reader.c, columnar/src/backend/columnar/columnar_tableam.c, columnar/src/include/columnar/columnar.h
Cache can be evected if still is in use, so it can trigger random memory problems or crash running process.
Fixed by keeping track of current chunk that is in use so we don't consider it for eviction.
Changed current cache coding style to align with rest of code.
=> [columnar] Cache eviction crash

columnar/src/backend/columnar/columnar_customscan.c
The current value of `0.9` (on a scale of `0.0` to `1.0`) means that most quals will not be pushed down and thereby no chunk elimination occurs.  this PR lowers that value to `0.4`, which seems to work well in testing against both the clickbench and warehouse benchmarks.
=> [columnar] modify default qual_pushdown_correlation_threshold

columnar/src/backend/columnar/columnar_metadata.c
* When stripe assignment for next parallel worker is executing we iterate sequentially to find next stripe that will be used. That could be expensive - especially if number of stripes for table is big. During this loop we are holding shared mutex that will abort if held to long.
* Fixed by using second column from index to faster assign stripe for worker.
=> [columnar] [bug] panic query on select count(*) from ..

columnar/src/backend/columnar/columnar_planner_hook.c, columnar/src/test/regress/expected/columnar_aggregates.out, columnar/src/test/regress/expected/columnar_aggregates_1.out, columnar/src/test/regress/sql/columnar_aggregates.sql
* Don't use vectorized aggregates if FILTER is used. FILTER is part of aggregate node execution - not part of custom scan.
=> [columnar] Don't use vectorized aggregates if FILTER is used

files/spilo/postgres-appliance/scripts/configure_spilo.py
Users couldn't actually use `pg_hint_plan` on Hydra Cloud; this preloads the extension and allows users to call `CREATE EXTENSION` which enables additional functionality.
`pg_hint_plan` is a bit unusual in than adding it to extwlist and then calling `CREATE EXTENSION` isn't sufficient to fully load the extension.
I've already tested the resulting build on a staging instance.
=> spilo: add pg_hint_plan to extwlist and shared_preload

columnar/src/backend/columnar/columnar_metadata.c, columnar/src/backend/columnar/columnar_tableam.c, columnar/src/include/columnar/columnar.h
As noted in #177, during a multi-insert, we were blindly inserting all data without doing any constraint or trigger checks.
This PR adds the constraint and trigger checks in.
This will likely have an affect on multi-insert (`COPY`) speed, but is now correct instead of allowing for duplicates when they should not be allowed.
=> [columnar] Force trigger and constraint checks after every multi-insert

columnar/src/backend/columnar/columnar_reader.c, columnar/src/test/regress/expected/columnar_types_without_comparison.out, columnar/src/test/regress/sql/columnar_types_without_comparison.sql
* If column type doesn't have comparison operator we are checking if class operator can be found. Use that operator for writing and reading chunks.
* Fixed existing test to show feature functionality
=> [columnar] Use class comparison operator for types which doesn't have one

columnar/src/backend/columnar/columnar_tableam.c
fixes #192 by porting in fix from citus https://github.com/citusdata/citus/pull/5962
I was not able to get TAP tests working correctly in our source tree, so did not include the TAP test, so here are the steps to reproduce (taken from https://github.com/citusdata/citus/issues/5958):
postgresql.conf
```
shared_preload_libraries=citus
shared_preload_libraries='citus'
vacuum_freeze_min_age = 50000
vacuum_freeze_table_age = 50000
synchronous_commit = off
fsync = off
```
psql:
```
CREATE EXTENSION columnar;
CREATE TABLE test_row(i int);
INSERT INTO test_row VALUES (1);
CREATE TABLE test_col(i int) USING columnar;
INSERT INTO test_col VALUES (1);
```
bash:
```
(for i in `seq 1 200000`; do echo "UPDATE test_row SET i = i + 1;"; done) | ./bin/psql -q -X postgres
```
psql:
```
select datname, …
```
=> [columnar] Port in citus freezing code for vacuum

columnar/src/backend/columnar/columnar_metadata.c, columnar/src/backend/columnar/columnar_tableam.c, columnar/src/test/regress/columnar_schedule, columnar/src/test/regress/expected/columnar_upsert.out, columnar/src/test/regress/sql/columnar_upsert.sql
This PR adds speculative insert (upsert) to the columnar extension.
As part of that, there is a new `spec_mask` column added to `columnar.row_mask`.  it is extremely important that the upgrade script be run to update the extension.
Note that this should be tested extensively before being merged, as it has a direct impact on data storage.
=> [columnar] speculative insert

Dockerfile
Fix pgxman install with the new syntax after introducing `--pg`
=> Fix pgxman install with the new syntax

third-party/pgxman/pgxman_14_spilo.yaml
Use the new `overwrite` syntax for Spilo pack to achieve the same thing. Ref: https://github.com/pgxman/pgxman/pull/112.
=> Use the new `overwrite` syntax for Spilo pack

Dockerfile
=> remove locale workaround

columnar/src/backend/columnar/columnar_metadata.c, columnar/src/backend/columnar/columnar_tableam.c, columnar/src/backend/columnar/columnar_writer.c, columnar/src/include/columnar/columnar_metadata.h, columnar/src/test/regress/expected/columnar_vacuum.out, columnar/src/test/regress/sql/columnar_vacuum.sql
there is an issue when dealing with very large fields (near 1gb) are inserted into a columnar store.  a vacuum (or auto-vacuum) is performed, which is unable to combine.
this fixes that, and decompression.
=> Vacuum large blocks

columnar/src/backend/columnar/columnar_metadata.c, columnar/src/backend/columnar/columnar_tableam.c, columnar/src/backend/columnar/columnar_writer.c, columnar/src/test/regress/expected/columnar_alter_set_type.out, columnar/src/test/regress/expected/columnar_insert.out, columnar/src/test/regress/expected/columnar_insert_1.out, columnar/src/test/regress/expected/columnar_insert_2.out, columnar/src/test/regress/expected/columnar_vacuum.out, columnar/src/test/regress/sql/columnar_insert.sql, columnar/src/test/regress/sql/columnar_vacuum.sql
Metadata table is on heap. If we try to construct metadata row bigger than 1GB insert will fail at that point. Limit maximum column size to be 256MB.
=> [columnar] HYD-761 Set maximum column size

.github/workflows/ci.yaml, Dockerfile.spilo
We are getting `initdb: error: invalid locale name “en_US.UTF-8”` in acceptance tests. This is related to https://github.com/docker-library/postgres/issues/1112. We are forcing UTF-8 as the locale for spilo image. Besides, this PR includes a fix to upload pg logs for spilo build. 
Successful splio build is in https://github.com/hydradatabase/hydra-internal/actions/runs/7506480250.
=> Force UTF-8 locale for spilo image

columnar/src/backend/columnar/columnar_tableam.c
during logical replication of large tables, multiple `MemoryContext`'s are created via `CreateColumnarScanMemoryContext()` and do not get removed, eventually resulting in the `OOM` killer killing off the replication process and forcibly restarting the database.
since a scan context can get used outside of an actual read, it did not make sense to delete it in `ColumnarEndRead()`, so individual scan contexts are deleted when the function that created them are about to end execution.
this eliminates the ever-growing of scan contexts that appear under `TopMemoryContext`, and fixes the leak.
=> [columnar] delete the scanContext whenever possible after creation

columnar/src/backend/columnar/columnar_planner_hook.c
* In presence of another custom scan, aggregator node will be still vectorized which can be problematic. Skip vectorization if custom scan is differnt than ColumnarScan.
=> [columnar] Skip vectorization if custom scan is not ColumnarScan

Dockerfile, Dockerfile.spilo, third-party/pgxman/pgxman_13.yaml, third-party/pgxman/pgxman_14.yaml, third-party/pgxman/pgxman_14_spilo.yaml, third-party/pgxman/pgxman_15.yaml
need to remerge this due to git failure on my part
=> Update pgxman download url and extension versions

columnar/src/backend/columnar/columnar_reader.c, columnar/src/test/regress/expected/columnar_alter_set_type.out, columnar/src/test/regress/expected/columnar_query.out, columnar/src/test/regress/sql/columnar_query.sql
When `chunk_group_row_limit` is bigger than 110000, there is a crash caused by `ReadStripeNextVector()`.
For example:
```sql
CREATE TABLE t1 (id int, info text) USING columnar;
CREATE TABLE t2 (id int, info text) USING columnar;
SELECT columnar.alter_columnar_table_set('t1', chunk_group_row_limit => '10000');
SELECT columnar.alter_columnar_table_set('t2', chunk_group_row_limit => '11000');
INSERT INTO t1 SELECT id, md5(id::text) FROM generate_series(1, 10000000) id;
INSERT INTO t2 SELECT id, md5(id::text) FROM generate_series(1, 10000000) id;
```
```sql
[local]:345317 postgres=# SELECT count(*) FROM t1;
count
----------
10000000
(1 row)
[local]:345317 postgres=# SELECT count(*) FROM t2;
server closed the connection unexpectedly
This probably means the server terminated abnormally
before …
```
=> Fix a server crash

columnar/src/backend/columnar/columnar_cache.c
The `found` variable in `ColumnarAddCacheEntry()` is only used in the `if-else`-branch.  It is true in `if`-branch, and false in the `else`-branch, so that the `dlist_push_tail()` is always executed in the `else`-branch, so the `found` variable is unnecessary.
=> Remove unnecessary variable

columnar/src/backend/columnar/columnar_tableam.c, columnar/src/test/regress/expected/columnar_alter_set_type.out, columnar/src/test/regress/expected/columnar_indexes.out, columnar/src/test/regress/expected/columnar_vacuum.out, columnar/src/test/regress/expected/columnar_vacuum_udf.out, columnar/src/test/regress/expected/columnar_vacuum_udf_1.out, columnar/src/test/regress/sql/columnar_indexes.sql, columnar/src/test/regress/sql/columnar_vacuum.sql, columnar/src/test/regress/sql/columnar_vacuum_udf.sql
when an index is being built, we should disable the column cache for the duration to stop multiple cache evictions on large tables.
=> [columnar] turn off caching when building an index

columnar/src/test/regress/expected/columnar_alter_set_type.out
fixes tests that inadvertently got broken during a merge.
=> [columnar] fix storage id for alter set type

Dockerfile.spilo, docker-bake.hcl, files/spilo/postgres-appliance/pgq_ticker.ini, files/spilo/postgres-appliance/scripts/configure_spilo.py, files/spilo/postgres-appliance/scripts/post_init.sh, files/spilo/postgres-appliance/scripts/spilo_commons.py, third-party/pgxman/pgxman_13_spilo.yaml
Upgrade Spilo image to the latest release: https://github.com/zalando/spilo/releases/tag/3.2-p2. The following changes are made:
* Point the base to upstream instead of our fork since the [`PGVERSION` fix](https://github.com/zalando/spilo/compare/master...hydradatabase:spilo:hydra-2.1-p9) was added in upstream
* Our fix to `pgq_ticker.ini` is not necessary because upstream updated it with [the same config](https://github.com/zalando/spilo/blob/3.2-p2/postgres-appliance/pgq_ticker.ini)
* Merge corresponding Spilo configs with upstream's
=> [HYD-890] Upgrade Spilo image to 3.2-p2

columnar/src/backend/columnar/columnar_reader.c, columnar/src/backend/columnar/vectorization/columnar_vector_types.c
This commit also changes the column type length judgment in `ReadChunkGroupNextVector()`.  According to Postgres code, not all platforms have `sizeof(Datum) == 8` [1], so it might be better to use `sizeof(Datum)` instead of the magic number 8.
[1] https://github.com/postgres/postgres/blob/master/src/include/postgres.h#L58
=> Avoid calling the get_typlen multiple times

columnar/src/backend/columnar/columnar.control, columnar/src/backend/columnar/sql/columnar--11.1-11--11.1-12.sql, columnar/src/backend/columnar/sql/udfs/alter_table_set_access_method/11.1-12.sql, columnar/src/test/regress/expected/columnar_alter_table_set_access_method.out, columnar/src/test/regress/sql/columnar_alter_table_set_access_method.sql
* We should be able to convert case sensitive schema name and table names. For case sensitive names function argument for `alter_table_set_access_method` should be like "Schema"."Table".
=> [columnar] Fix for case sensitive schema names (#264)

columnar/src/test/regress/expected/columnar_query.out, columnar/src/test/regress/sql/columnar_query.sql
Fix flap in column_query test
In my PostgreSQL build in test output I had at first rows beginning from letters, not numbers.
Then when I had added ordering output was as in original file: at first numbers, then letters.
**Flap:**
```
----------------------------------+-------
a87ff679a2f3e71d9181a67b7542122c | 49950
c4ca4238a0b923820dcc509a6f75849b | 49950
c81e728d9d4c2f636f067f89cc14862c | 49950
c9f0f895fb98ab9159f51fd0297e236d | 49950
d3d9446802a44259755d38e6d163e820 | 49950
e4da3b7fbbce2345d7772b0674a318d5 | 49950
eccbc87e4b5ce2fe28308fd9f2a7baf3 | 49950
1679091c5a880faf6fb5e6087eb1b2dc | 49950
45c48cce2e2d7fbdea1afc51c7c6ad26 | 49950
8f14e45fceea167a5a36dedd4bea2543 | 49950
(10 rows)
```
**Correct:**
```
----------------------------------+-------
1679091c5a880faf6fb5e6087eb1b2dc | …
```
=> fix flap in column_query test

columnar/src/backend/columnar/columnar_planner_hook.c
[In function IsCreateTableAs in columnar_planner_hook.c](https://github.com/hydradatabase/hydra/blob/47354c2b576b0092786a5578049d998bd7c2287f/columnar/src/backend/columnar/columnar_planner_hook.c#L412) there is variable `int16 i` uses as iteration variable.
It works fine on small requests, but when there is large script it causes overflow with consequences in such way:
1. `i = INT16_MAX` (script is large)
2. `++i = INT16_MIN` (overflow)
3. for loop condition is not met - loop ends
4. `i == -32768`
5. `haystack[i] = '\0'` == `haystack[-32768] = '\0';` - we overwrite some memory address
Steps to reproduce:
1. Create and install (not `CREATE EXTENSION` yet) stub extension with large sql file. I.e. 10000 lines of `select 1;`
2. Run DB and PSQL (next execute in PSQL)
3. Execute `CREATE …
=> Fix overflow in int16 variable
