hydradatabase/hydra

README.md

Align the description with our marketing pitch. Suggestions by @jhydra12

[HYD-62] Align the description with our marketing pitch

---

README.md

Add doc link

---

.github/workflows/ci.yaml

master branch was renamed to main. Fixing CI to reflect it.

Publish image on main branch

---

acceptance/hydra_test.go

Wait for readines endpoint before proceeding with the actual acceptance tests. This helps eliminate the flakiness of acceptance tests.

[HYD-90] Wait for readines endpoint before proceeding with the actual acceptance tests

---

Makefile

Align spilo version with the CI build in Makefile

Align spilo version in Makefile

---

.github/workflows/ci.yaml
acceptance/hydra_test.go

Update acceptance tests for `columnar.alter_columnar_table_set`. Depends on https://github.com/HydrasDB/citus/pull/13

[HYD-148] Update acceptance tests for `columnar.alter_columnar_table_set`

---

README.md

Fix a bunch of 404s

---

README.md

Update repo stars link

---

.github/workflows/build_spilo.yaml
.github/workflows/ci.yaml

fix github actions parse error, raise timeouts to 15m

[ci] fix error in github actions file

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
bin/autolink_changelog.rb

add CHANGELOG

---

docker-bake.hcl

recent release of bookworm broke the build; this pins us to bullseye until we can make the changes needed to support bookworm.

pin to bullseye

---

columnar/src/backend/columnar/columnar_tableam.c

When running the vacuum UDF against very large tables, memory can be exhausted because of allocations in reads and writes.  This adds a fence around each read and write operation to create a new memory context and delete it between iterations.

[columnar] Adds memory fences around stripe combinations and reorganization

---

docker-compose.yml
files/postgres/postgresql.conf

This now matches what we use in our Hydra hosted service. By doing so, we will avoid some issues where data has been inserted into the database but not analyzed.

Modify autovacuum settings in open source image

---

columnar/src/backend/columnar/columnar_customscan.c

This reverts commit e7038b96bc270e4341f9fbf33abbf29439f60521.
After review of benchmarks, I found the performance impact of this change to be significant. By adjusting the autovacuum settings to `analyze` more frequently, and/or by running `analyze` after inserting a large amount of data (a common best practice for Postgres), users should be able to avoid the issue which we were fixing in #98.
In other words, making optimized databases slower so unoptimized databases can run faster wasn't a good tradeoff. Best of both worlds would be even better, but for now we'll take the faster result.

Revert "[columnar] Adjust plan for parallel workers (#98)"

---

CHANGELOG.md

summarize each release in the changelog.
I went with passive voice here; writing it in first person plural ("we") would be a bit more natural.

add summaries to changelog

---

BENCHMARKS.md
README.md

explain and display results from Bencher

add BENCHMARKS.md

---

columnar/src/backend/columnar/columnar.control
columnar/src/backend/columnar/sql/columnar--11.1-7--11.1-8.sql
columnar/src/backend/columnar/sql/udfs/alter_table_set_access_method/11.1-8.sql

* When checking for table constraint IF stament should have value to compare against.

[columnar] Fix for columnar.alter_table_set_access_method

---

.github/workflows/ci.yaml
Dockerfile
third-party/pgxman/pgxman_13.yaml
third-party/pgxman/pgxman_14.yaml
third-party/pgxman/pgxman_14_spilo.yaml
third-party/pgxman/pgxman_15.yaml

@mkaruza this should fix the build on your PR; rebase after this is merged.

update pgvector to 0.5.1

---

third-party/pgxman/pgxman_13.yaml
third-party/pgxman/pgxman_14.yaml
third-party/pgxman/pgxman_14_spilo.yaml
third-party/pgxman/pgxman_15.yaml

Update to the latest `postgres` section for pgxman.yaml.
Ref: https://github.com/pgxman/pgxman/pull/84

Update to the latest `postgres` section for pgxman.yaml

---

Makefile

Usage:
```
POSTGRES_BASE_VERSION=16 PLATFORM=linux/amd64,linux/arm64 POSTGRES_IMAGE=ghcr.io/hydradatabase/hydra:16 make docker_push_postgres
```

Add make task to docker push locally

---

columnar/src/backend/columnar/columnar.c
columnar/src/backend/columnar/columnar_tableam.c

Compatibility with PG16 after custom index scan feature.
fixes #209

[columnar] PG16 compatibility after custom index scan feature

---

Dockerfile
Dockerfile.spilo
third-party/pgxman/pgxman_13.yaml
third-party/pgxman/pgxman_14.yaml
third-party/pgxman/pgxman_14_spilo.yaml
third-party/pgxman/pgxman_15.yaml

* Update to the official pgxman download url
* Update extension versions

Update pgxman download url and extension versions

---

third-party/pgxman/pgxman_13.yaml
third-party/pgxman/pgxman_14.yaml
third-party/pgxman/pgxman_14_spilo.yaml
third-party/pgxman/pgxman_15.yaml
third-party/pgxman/pgxman_16.yaml

Unify `pg_hint_plan` into the same name with different versions for different pg versions. See https://github.com/pgxman/buildkit/pull/75

Unify `pg_hint_plan` into the same name with different versions

---

columnar/src/test/regress/input/columnar_load.source
columnar/src/test/regress/output/columnar_load.source

Fix copy-and-paste in regression test comment

---

columnar/src/backend/columnar/columnar_customscan.c
columnar/src/backend/columnar/columnar_planner_hook.c
columnar/src/test/regress/expected/columnar_aggregates_2.out

This commit also fixes some typos.

Remove the unnecessary return statements

---

columnar/src/test/regress/expected/columnar_aggregates.out

Forget to update columnar_aggregates expected result

---

columnar/src/backend/columnar/sql/udfs/alter_table_set_access_method/11.1-11.sql
columnar/src/backend/columnar/sql/udfs/alter_table_set_access_method/latest.sql
columnar/src/test/regress/expected/columnar_chunk_filtering.out
columnar/src/test/regress/expected/columnar_recursive.out
columnar/src/test/regress/expected/columnar_tableoptions.out
columnar/src/test/regress/expected/columnar_truncate.out
columnar/src/test/regress/expected/columnar_types_without_comparison.out
columnar/src/test/regress/sql/columnar_chunk_filtering.sql
columnar/src/test/regress/sql/columnar_recursive.sql
columnar/src/test/regress/sql/columnar_tableoptions.sql
columnar/src/test/regress/sql/columnar_truncate.sql
columnar/src/test/regress/sql/columnar_types_without_comparison.sql

Fix some typos

---

columnar/src/backend/columnar/columnar_metadata.c

The InsertTupleAndEnforceConstraints() constructed tuple on-the-fly, and on other reference, so we can safely set shouldFree to true for ExecStoreHeapTuple() to avoid duplicate memory allocation.
Here is my environment:
```shell
$ uname -a
Linux dell-dev 6.5.0-15-generic #15~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 12 18:54:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
$ free -h
total        used        free      shared  buff/cache   available
Mem:           7.7Gi       3.6Gi       2.0Gi       403Mi       2.0Gi       3.3Gi
Swap:             0B          0B          0B
```
The test case comes from regression test columnar_vaccum.sql.
``` …
```

Fix an out-of-memory when inserting large values
